### ISSUE TITLE
热门搜索可不可以增加「换一批」的功能

### ISSUE THREAD

**Issue by geekdmm0xff** [ko1o/PYSearch#10]
因为我看到是  label，不能像 collectioview 那样直接 reloaddata

**Comment by iphone5solo** [comment]
谢谢您的反馈。根据您的反馈。我开放了热门搜索数组属性，你可以在点击换一批时重新给hotSearches赋值即可！ @geekdmm0xff

**Comment by app111** [comment]
刚才发现这地方有个bug，第一次给的数组为空，后续怎么给值都显示不了了，因为设了hidden=YES, 而没有根据实际值设hidden=NO
![qq20161115-0](https://cloud.githubusercontent.com/assets/1449284/20290426/d454b2da-ab1a-11e6-928b-a714053d0f12.png)
