### ISSUE TITLE
更细iOS11,搜索框不见了

### ISSUE THREAD

**Issue by Pro-SY** [ko1o/PYSearch#107]
更新了iOS11之后,搜索框消失了,请问怎么适配?谢谢

**Comment by iphone5solo** [comment]
@Pro-SY  更新到最新版 再试试！

**Comment by iphone5solo** [comment]
@Pro-SY 最新版本已经完成适配，欢迎更新测试！

**Comment by yt19860606** [comment]
更新到最新的，自定义左侧搜索框和添加返回按钮后，在debug模式下有搜索框，在release下却没有搜索框啦？为什么
