### ISSUE TITLE
ios11 搜索框变形，取消按钮没居中

### ISSUE THREAD

**Issue by ningcol** [ko1o/PYSearch#108]
搜索框变形，取消按钮没居中

**Comment by yrming** [comment]
iOS 11 下取消按钮紧挨着搜索框

**Comment by JHLeeVip** [comment]
iOS 11下搜索框变形,取消按钮紧挨着搜索框,希望能尽快优化,谢谢👍

**Comment by iphone5solo** [comment]
@ningcol @yrming @JHLeeVip 最新版本已经完成适配，欢迎更新测试！

**Comment by MuZiLee** [comment]
iOS 11.2还是变型的,点击搜索,再返回,_searchBar和_searchTextField的x居然居中了!!!!!
用mas_makeConstraints:约束都没有用.这也太神奇了吧?
