### ISSUE TITLE
iOS11 返回按钮消失了

### ISSUE THREAD

**Issue by qiaoxiyang** [ko1o/PYSearch#124]
在iOS11上，返回按钮不见了

**Comment by iphone5solo** [comment]
请使用最新版！

**Comment by qiaoxiyang** [comment]
使用的就是最新版，我用你的demo，将presentViewController改成了pushViewController也是不显示返回按钮的，你可以在你的demo上试一下。

**Comment by iphone5solo** [comment]
是没有返回按钮了，被取消按钮代替了！


原始邮件
发件人:iOSXiaoQiaonotifications@github.com
收件人:iphone5solo/PYSearchPYSearch@noreply.github.com
抄送:CoderKo1o499491531@qq.com; Commentcomment@noreply.github.com
发送时间:2017年10月23日(周一) 18:36
主题:Re: [iphone5solo/PYSearch] iOS11 返回按钮消失了 (#124)


使用的就是最新版，我用你的demo，将presentViewController改成了pushViewController也是不显示返回按钮的，你可以在你的demo上试一下。

**Comment by lucifer717** [comment]
有点没理解  iOS11上返回按钮不能自定义吗？
