### ISSUE TITLE
更新到最新版之后,搜索时<取消>按钮不见了,变成了...

### ISSUE THREAD

**Issue by Starryxu** [ko1o/PYSearch#127]
更新到最新版之后,搜索时<取消>按钮不见了,变成了...

**Comment by ko1o** [comment]
@Starryxu  请提供下 系统版本号 和 模拟器型号

**Comment by Starryxu** [comment]
模拟器没有问题,实在真机上面,iPhone 7 Plus  iOS 11.2 bate

**Comment by Starryxu** [comment]
https://pan.baidu.com/s/1nvkPD8X

**Comment by ko1o** [comment]
@Starryxu 这样的话 建议在源码里面修改下取消按钮的宽度即可，我这边没有真机 也不方便调试！

**Comment by ko1o** [comment]
@Starryxu 或者你可以更新到最新版，然后通过设置以下操作进行按钮宽度设置
```OBJC
    UIButton *cancelButton = searchViewController.cancelButton.customView;
    cancelButton.py_width = 88;
```

**Comment by Starryxu** [comment]
OK, 已经改成了cancelButton.py_width += 10 测试没有问题

**Comment by ko1o** [comment]
👌
