### ISSUE TITLE
如何才能添加 scopeBar？

### ISSUE THREAD

**Issue by karaschee** [ko1o/PYSearch#130]
想在搜索框下面加一组 tab，用于切换当前搜索类型。例如知乎的：
![wechatimg97](https://user-images.githubusercontent.com/2161243/32716791-42d782ec-c892-11e7-81a6-d403cb71017f.gif)
请问有比较方便的方法吗？

**Comment by ko1o** [comment]
建议自己实现！

**Comment by karaschee** [comment]
好的，今天在 PYSearchResultShowModeEmbed Style 的 resultController 里，用 Table View Section 里做了一个 tabs。
