### ISSUE TITLE
在 iOS 11 上，present 出来后，“取消”两个字成了 ...

### ISSUE THREAD

**Issue by shangleixun** [ko1o/PYSearch#134]
我看了可能是 searchBar 的 width 太宽，把 cancelButton 的 width 挤窄了，所以就成了这样了？在 iOS 10 上没有这个问题。

**Comment by shiweifu** [comment]
https://stackoverflow.com/questions/44442573/navigation-bar-rightbaritem-image-button-bug-ios-11

暂时用这里的方式解决了问题，我感觉这是iOS 11的 bug
