### ISSUE TITLE
searchBar 关标有从左向右出现的动画

### ISSUE THREAD

**Issue by Beyond-Chao** [ko1o/PYSearch#157]
这个动画是系统的嘛？请问如何去掉这个动画？
UISearchBar 弹出键盘的速度比UITextField慢许多, 请问如何优化键盘弹出速度

**Comment by CoderSimonWong** [comment]
+1

**Comment by CoderSimonWong** [comment]
iOS 11 Bug。我看到有几个其他的app也会有同样的问题，如果想好的，要自定义SearchBar
