### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [ko1o/PYSearch#165]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by ko1o** [comment]
@anharismail Welcome！Pull request please.

**Comment by anharismail** [comment]
Hello, Sir @ko1o . These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

### Version 1
![pysearch ver 1](https://user-images.githubusercontent.com/37614260/40469743-b816975e-5f5b-11e8-8559-f7e5646872d4.png)
### Version 2
![pysearch ver 2](https://user-images.githubusercontent.com/37614260/40469744-b854292a-5f5b-11e8-9a5f-ec050ccb2a39.png)

**Comment by ko1o** [comment]
@anharismail Nice ! Can you provide two pictures of the red box mark in the picture? like this.
![image](https://user-images.githubusercontent.com/13819507/40475312-ded40288-5f73-11e8-82b0-69bc5f9b7493.png)

**Comment by anharismail** [comment]
Hello Sir @ko1o , could you mind if you place my logo design on your project Readme?
Thanks before :)

**Comment by ko1o** [comment]
@anharismail You can add your logo at the top of Readme like this and pull a request!
![image](https://user-images.githubusercontent.com/13819507/40601376-82e40178-6287-11e8-932d-2cd5ecf5ef34.png)
