### ISSUE TITLE
返回手势失效，按钮和搜索框重叠

### ISSUE THREAD

**Issue by Wangmafei** [ko1o/PYSearch#168]
![image](https://user-images.githubusercontent.com/9606438/40872992-bf295fe6-668a-11e8-9fe6-721aee0d79bb.png)

**Comment by ko1o** [comment]
@Wangmafei 请问使用的是最新版本吗？ 最新版本的push需要设置`PYSearchViewControllerShowMode`属性为`PYSearchViewControllerShowModePush`

**Comment by TheLittleBoy** [comment]
demo直接运行就出现异常。 iOS 11.4  ，iPad ， 版本：0.8.9
