### ISSUE TITLE
demo连续多次进入搜索结果，然后返回，左侧返回按钮和箭头一直往左移，边缘返回手势失效

### ISSUE THREAD

**Issue by yuanzhiying** [ko1o/PYSearch#175]
同标题
![wechatimg15](https://user-images.githubusercontent.com/9746693/41948225-4b9324aa-79ee-11e8-96fc-aa1d7e9cbf67.jpeg)
![wechatimg17](https://user-images.githubusercontent.com/9746693/41948226-4bd3dd74-79ee-11e8-84ca-4abf501c72a5.jpeg)
<img width="415" alt="wx20180627-093827 2x" src="https://user-images.githubusercontent.com/9746693/41948227-4c145aca-79ee-11e8-8009-314d07522742.png">

**Comment by ko1o** [comment]
@yuanzhiying 我按照你说的试了下 没有你说的问题 麻烦可以发一份有问题的Demo到我邮箱上吗？ 邮箱：mambaxie@foxmail.com

**Comment by ko1o** [comment]
@yuanzhiying 现在已经修复，谢谢反馈！

**Comment by zezezea** [comment]
iOS 12 仍能出现这个问题
