### ISSUE TITLE
关于搜索框中光标飘的建议

### ISSUE THREAD

**Issue by vast0608** [ko1o/PYSearch#179]
由于每次弹出搜索界面时，总会给人一种光标飘过来的感觉，显得有点突兀，所以我找到了以下解决办法，不足之处希望指正。（见图一、图二）

![图一](https://user-images.githubusercontent.com/18329843/42980557-72b50872-8c0a-11e8-9ae5-1b84b4789981.png)

![图二](https://user-images.githubusercontent.com/18329843/42980602-aae3dd68-8c0a-11e8-8fea-aef4feef16cd.png)

**Comment by ko1o** [comment]
欢迎Pull request！

**Comment by Kejiasir** [comment]
@vast0608 咋整的，图挂了，dalao。。。

**Comment by vast0608** [comment]
@Kejiasir 图没挂，可能是网络加载慢点原因吧

**Comment by TianzhuChen** [comment]
图挂了

**Comment by baocang** [comment]
@vast0608 ,你图片有问题，我下载下来能看，在chrome里面不能看。
