### ISSUE TITLE
关于光标偏移问题的解决方法

### ISSUE THREAD

**Issue by MrLanger** [ko1o/PYSearch#187]
只需在源码426行self.searchBar = searchBar;前面加一行代码：[searchBar becomeFirstResponder];即可

我自己测试是可以解决的，只是不确定能不能解决所有人的问题，如果真的解决了请给我留一下言，哈哈

**Comment by glary** [comment]
[UIView performWithoutAnimation:^{
        [self.searchBar becomeFirstResponder];
 }];

**Comment by baocang** [comment]
@MrLanger  这个方法不错
