### ISSUE TITLE
这个库问题越来越多, 目前不再维护了吧?

### ISSUE THREAD

**Issue by xiaohange** [ko1o/PYSearch#195]

**Comment by ko1o** [comment]
@xiaohange 最新项目比较紧哈 会尽快找个时间修复下问题  还是会维护的 放心！

**Comment by xiaohange** [comment]
@ko1o 目前iOS10.3 会频繁出现错误:

1.
```
no UICollectionViewLayoutAttributes instance for -layoutAttributesForItemAtIndexPath: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}
CoreFoundation ___exceptionPreprocess
```

2.

```
no UICollectionViewLayoutAttributes instance for -layoutAttributesForItemAtIndexPath: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}

ZhuziyeProject -[PYSearchViewController saveSearchCacheAndRefreshView]
```

**Comment by ko1o** [comment]
@xiaohange 麻烦你把频繁出现的问题写个demo 发一下 499491531@qq.com

**Comment by baocang** [comment]
@xiaohange @ko1o 还是放 github上面更好吧？大家一起看看。你的PYSearch我也用了的呢。

**Comment by ko1o** [comment]
@baocang 谢谢为本项目做的贡献~

**Comment by xiaohange** [comment]
@baocang 如果有问题就问, 请问误导了什么?

**Comment by baocang** [comment]
@xiaohange 问题确实可以随便问，只是这个 ISSUE 标题有误导性，因为看起来错误不是属于 PYSearch 本身的。 如果问题仍然没有解决，非常欢迎你详细描述下问题，最好放 GitHub 上一个demo。不知道是不是你在哪里用了UICollectionView，用了自定义布局。或者用了别的库用了UICollectionView。这里只能知道可能 UICollectionView 中某一项没有对应的 UICollectionViewLayoutAttributes。
由于这个库确实也在维护，你的问题我看来可能也不属于这个库的问题。

对于问题本身，我们仍然愿意帮助你一起解决。希望 @xiaohange 能给予理解。

**Comment by xiaohange** [comment]
@baocang 改下标题就可以了
