### ISSUE TITLE
点击热门搜索代理不走

### ISSUE THREAD

**Issue by bobyang5437** [ko1o/PYSearch#201]
- (void)searchViewController:(PYSearchViewController *)searchViewController
   didSelectHotSearchAtIndex:(NSInteger)index;
代理不走这个方法

**Comment by ko1o** [comment]
![image](https://user-images.githubusercontent.com/13819507/47716443-a6aa4700-dc7d-11e8-927f-70876cfae81d.png)
在这个地方打断点调试一下 看看是什么原因

**Comment by baocang** [comment]
@bobyang5437 应该是 `searchViewController:didSelectHotSearchAtIndex:searchText:` 而不是 `searchViewController:didSelectHotSearchAtIndex:` 吧？我稍微看了下，没能重现，明天好好看看。你系统版本以及如何使用的能详细描述下吗。

**Comment by bobyang5437** [comment]
@baocang  代理方法我简写了下，我就在源demo上测试了
![image](https://user-images.githubusercontent.com/15794956/47759862-ab5a1400-dcec-11e8-91fe-2fad5f0c778d.png)
设置为这个类型，必然不走代理。最新版本系统和xcode。

**Comment by baocang** [comment]
@bobyang5437 什么叫做简写了下?  另外很抱歉我描述的不清楚，实际上我想知道的是你 iOS 系统版本，稍后我会加个issue_template的PR方便我们提issue的时候获得必备信息。

**Comment by ko1o** [comment]
@bobyang5437 已经修复了 还原下载最新版本

**Comment by baocang** [comment]
@ko1o 👌
