### ISSUE TITLE
可以交换搜索历史和热门搜索的位置吗？

### ISSUE THREAD

**Issue by CCBrother** [ko1o/PYSearch#213]
### 问题描述

可以让历史记录显示在热门搜索前面吗？
#### 预期结果

<img width="206" alt="图片" src="https://user-images.githubusercontent.com/14049399/56598928-10e9e600-6628-11e9-9f04-507f4b0a664b.png">

### 版本信息

- PYSearch：vX.X.X
- Xcode：vX.X.X
- macOS：vX.X.X
- CocoaPods：vX.X.X

**Comment by ko1o** [comment]
@CCBrother `swapHotSeachWithSearchHistory` 设为YES.

**Comment by CCBrother** [comment]
目前我用的版本没有看到这个属性，最新版本有这个属性了？

**Comment by CCBrother** [comment]
> @CCBrother `swapHotSeachWithSearchHistory` 设为YES.

新版本看到了，多谢多谢~

**Comment by CCBrother** [comment]
新版本看到了，多谢多谢~
