### ISSUE TITLE
同一个项目中用多个 PYSearchViewController  

### ISSUE THREAD

**Issue by iDwyane** [ko1o/PYSearch#214]
同一个项目中用多个 PYSearchViewController  ，就会记住同样的搜索历史记录，但是是不同的搜索界面，如何区分每个不同历史记录。比如在在搜索商品界面搜索“牛奶”，然后再搜索通讯录界面搜索“10086”，历史记录就变成了牛奶 和 10086，但是我要的是分开记录，不同界面搜索的只记录其自己的，不要一起记录。

**Comment by ko1o** [comment]
@iDwyane  只需要设置下面的属性，自定义搜索记录缓存路径就可以区分开了。
```objc
/**
 The path of cache search record, default is `PYSEARCH_SEARCH_HISTORY_CACHE_PATH`.
 */
@property (nonatomic, copy) NSString *searchHistoriesCachePath;
```
