### ISSUE TITLE
用一个UINavigationController包了searchViewController，present出来后，出现如图问题

### ISSUE THREAD

**Issue by CCBrother** [ko1o/PYSearch#215]
### 问题描述
用一个UINavigationController包了searchViewController，present出来后，出现如图问题，页面会置顶了

代码如下：
self.searchNav = [[UINavigationController alloc] initWithRootViewController:searchViewController];
            [self presentViewController:self.searchNav  animated:NO completion:nil];

#### 重现步骤
<img width="330" alt="图片" src="https://user-images.githubusercontent.com/14049399/56675568-0181a000-66ef-11e9-836e-5119e13cb896.png">

### 版本信息

- PYSearch：vX.X.X
- Xcode：vX.X.X
- macOS：vX.X.X
- CocoaPods：vX.X.X

**Comment by ko1o** [comment]
@CCBrother 可能是iOS 11.0以后 tableview的问题，试试添加一下代码：
```objc
    if (@available(iOS 11.0, *)) {
        [UITableView appearance].estimatedRowHeight = 0;
        [UITableView appearance].estimatedSectionFooterHeight = 0;
        [UITableView appearance].estimatedSectionHeaderHeight = 0;
        [UITableView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        [UIScrollView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    }
```

**Comment by CCBrother** [comment]
还是不行，看视图，tableview没问题，是历史记录的那个view，上移了

**Comment by CCBrother** [comment]
加一句这个 self.searchNav.navigationBar.translucent = NO; 就可以了，导航栏问题
