### ISSUE TITLE
能不能来个swift的Demo？

### ISSUE THREAD

**Issue by lh948** [ko1o/PYSearch#222]
如题

**Comment by ko1o** [comment]
因为本人swift 接触比较少。 期待哪个swift大佬 帮忙写个 swift demo !

**Comment by yangwei0401** [comment]
[PYSearchExample_Swift.zip](https://github.com/ko1o/PYSearch/files/3284935/PYSearchExample_Swift.zip)

**Comment by lh948** [comment]
谢谢大牛
