### ISSUE TITLE
当搜索历史为默认样式的时候 “搜索历史”的字号与“热门搜索”的字号不一致  请问有什么好的解决方案

### ISSUE THREAD

**Issue by mixi9527** [ko1o/PYSearch#28]

**Comment by momodou4ever** [comment]
<img width="621" alt="wx20161214-171619 2x" src="https://cloud.githubusercontent.com/assets/6284023/21176304/122eed1a-c221-11e6-822b-c6fd6c301555.png">

**Comment by iphone5solo** [comment]
![image](https://cloud.githubusercontent.com/assets/13819507/21177905/19983e2e-c228-11e6-9edc-56d87c1a604d.png)
@momodou4ever  已经提供了 hotSearchHeader 可以直接设置font

**Comment by momodou4ever** [comment]
@iphone5solo 这个热门搜索可以设置大小我知道  就是下面的历史搜索不知道怎么设置

**Comment by momodou4ever** [comment]
@iphone5solo 
/** 搜索历史标题,只有当PYSearchHistoryStyle != PYSearchHistoryStyleCell才有值 */
@property (nonatomic, weak) UILabel *searchHistoryHeader; 
你这里做了判断 默认样式它是没有值的

**Comment by momodou4ever** [comment]
@iphone5solo 直接输入搜索关键字以后回车 好像没有做保存历史搜索的操作 必须点击建议列表才能保存此次搜索历史

**Comment by iphone5solo** [comment]
下面的搜索历史是section的headerView，要修改就是自定义headerView
 关于直接搜索没有添加到搜索历史的BUG昨天已经修复，下载最新版即可

**Comment by mixi9527** [comment]
closed
